# Generated by Django 3.2.19 on 2023-05-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order_item_total',
            new_name='lineitem_total',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
